Controllers/AreasController.cs
using BeanSceneSystem.Data;
using BeanSceneSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;

namespace BeanSceneSystem.Controllers
{
    public class AreasController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public AreasController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        // GET Areas
        public async Task<IActionResult> Index()
        {
            return dbContext.Areas != null ?
                        View(await dbContext.Areas.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Areas'  is null.");
        }

        // GET Areas Details

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || dbContext.Areas == null)
            {
                return NotFound();
            }

            var area = await dbContext.Areas
                .FirstOrDefaultAsync(m => m.AreaID == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        // GET Create Areas
        public IActionResult Create()
        {
            return View();
        }


        // POST Create Areas
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AreaID,AreaName")] Area area)
        {
            if (ModelState.IsValid)
            {
                dbContext.Add(area);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(area);
        }

        // GET Areas Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || dbContext.Areas == null)
            {
                return NotFound();
            }

            var area = await dbContext.Areas.FindAsync(id);
            if (area == null)
            {
                return NotFound();
            }
            return View(area);
        }

        // POST Areas Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AreaID,AreaName")] Area area)
        {
            if (id != area.AreaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    dbContext.Update(area);
                    await dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AreaExists(area.AreaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(area);
        }

        // GET Areas Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || dbContext.Areas == null)
            {
                return NotFound();
            }

            var area = await dbContext.Areas
                .FirstOrDefaultAsync(m => m.AreaID == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        // POST Areas Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (dbContext.Areas == null)
            {
                return Problem("Entity set 'RestaurantContext.Areas'  is null.");
            }
            var area = await dbContext.Areas.FindAsync(id);
            if (area != null)
            {
                dbContext.Areas.Remove(area);
            }

            await dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool AreaExists(int id)
        {
            return (dbContext.Areas?.Any(e => e.AreaID == id)).GetValueOrDefault();
        }
    }
}

Controllers/StaffsController.cs
using BeanSceneSystem.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BeanSceneSystem.Models;
using Microsoft.AspNetCore.Authorization;

namespace BeanSceneSystem.Controllers
{
    [Authorize]
    public class StaffsController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public StaffsController(ApplicationDbContext context)
        {
            dbContext = context;
        }

        // GET Staffs
        public async Task<IActionResult> Index()
        {
            return dbContext.Staffs != null ?
                        View(await dbContext.Staffs.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Staffs'  is null.");
        }

        // GET Staffs Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || dbContext.Staffs == null)
            {
                return NotFound();
            }

            var staff = await dbContext.Staffs
                .FirstOrDefaultAsync(m => m.StaffID == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET Staffs Create
        public IActionResult Create()
        {
            return View();
        }

        // POST Staffs Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StaffID,StaffType,FirstName,LastName,Email,Phone,Password")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                dbContext.Add(staff);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET Staffs Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || dbContext.Staffs == null)
            {
                return NotFound();
            }

            var staff = await dbContext.Staffs.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // POST Staffs Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StaffID,StaffType,FirstName,LastName,Email,Phone,Password")] Staff staff)
        {
            if (id != staff.StaffID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    dbContext.Update(staff);
                    await dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.StaffID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET Staffs Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || dbContext.Staffs == null)
            {
                return NotFound();
            }

            var staff = await dbContext.Staffs
                .FirstOrDefaultAsync(m => m.StaffID == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST Staffs Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (dbContext.Staffs == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Staffs'  is null.");
            }
            var staff = await dbContext.Staffs.FindAsync(id);
            if (staff != null)
            {
                dbContext.Staffs.Remove(staff);
            }

            await dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return (dbContext.Staffs?.Any(e => e.StaffID == id)).GetValueOrDefault();
        }
    }
}

Controllers/TablesController.cs
using BeanSceneSystem.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeanSceneSystem.Models;

namespace BeanSceneSystem.Controllers
{
    public class TablesController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public TablesController(ApplicationDbContext context)
        {
            dbContext = context;
        }

        // GET Tables
        public async Task<IActionResult> Index()
        {
            var context = dbContext.Tables.Include(r => r.Area);
            return View(await context.ToListAsync());
        }

        // GET Tables Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || dbContext.Tables == null)
            {
                return NotFound();
            }

            var table = await dbContext.Tables
                .Include(r => r.Area)
                .FirstOrDefaultAsync(m => m.TableID == id);
            if (table == null)
            {
                return NotFound();
            }

            return View(table);
        }

        // GET Tables Create
        public IActionResult Create()
        {
            ViewData["AreaID"] = new SelectList(dbContext.Areas, "AreaID", "AreaName");
            return View();
        }

        // POST Tables Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TableID, AreaID, TableName, TableStatus")] Table table)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    dbContext.Add(table);
                    await dbContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    // Log the exception or handle it appropriately
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists " +
                        "see your system administrator.");
                    // You can log the exception for detailed debugging
                    Console.WriteLine(ex);
                }
            }

            // If ModelState is not valid, populate ViewData and return the view with errors
            ViewData["AreaID"] = new SelectList(dbContext.Areas, "AreaID", "AreaName", table.AreaID);
            return View(table);
        }



        // GET Tables Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || dbContext.Tables == null)
            {
                return NotFound();
            }

            var table = await dbContext.Tables.FindAsync(id);
            if (table == null)
            {
                return NotFound();
            }
            ViewData["AreaID"] = new SelectList(dbContext.Areas, "AreaID", "AreaName", table.AreaID);
            return View(table);
        }

        // POST Tables Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TableID,AreaID,TableName,TableStatus")] Table table)
        {
            if (id != table.TableID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    dbContext.Update(table);
                    await dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TableExists(table.TableID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AreaID"] = new SelectList(dbContext.Areas, "AreaID", "AreaName", table.AreaID);
            return View(table);
        }

        // GET Tables Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || dbContext.Tables == null)
            {
                return NotFound();
            }

            var table = await dbContext.Tables
                .Include(r => r.Area)
                .FirstOrDefaultAsync(m => m.TableID == id);
            if (table == null)
            {
                return NotFound();
            }

            return View(table);
        }

        // POST Tables Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (dbContext.Tables == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Tables'  is null.");
            }
            var table = await dbContext.Tables.FindAsync(id);
            if (table != null)
            {
                dbContext.Tables.Remove(table);
            }

            await dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TableExists(int id)
        {
            return (dbContext.Tables?.Any(e => e.TableID == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeanSceneSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BeanSceneSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bean Scene</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Areas" asp-action="Index">Areas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tables" asp-action="Index">Tables</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Schedules" asp-action="Index">Schedules</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Staffs" asp-action="Index">Staff Details</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="StaffPermissions" asp-action="Index">Staff Permissions</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BeanSceneSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>